version: '3.9'
services:
  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD= 'admin'
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - /home/ubuntu/database:/var/lib/postgresql/data:rw   
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  frontend:
    image: bromx/frontend
    command: npx serve build
    ports:
      - "3000:3000"
    depends_on:
      - web




