version: '3'
services:
  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD= 'admin'
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - /home/ubuntu/database:/var/lib/postgresql/data:rw 
    networks:
      - mynetwork
  web:
    build: .
    image: backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # depends_on:
    #   - db
    networks:
      - mynetwork

  frontend:
    image: frontend
    container_name: frontend
    command: npx serve build
    ports:
      - "3030:3000"
    networks:
      - mynetwork
    # depends_on:
    #   - web
      
networks:
  mynetwork:



