apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: ecom
  DATABASE_USER: $(DATABASE_USER)
  DATABASE_PASSWORD: $(DATABASE_PASSWORD)